# Change these first
owner: bridgewater-state-university # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: BSU Public Website
    url: https://www.bridgew.edu
  - name: Institutional Catalog
    url: https://catalog.bridgew.edu

status-website:
  theme: light
  css: "img.svelte-a08hsz{max-height:50px} .container{max-width:unset;width:80%} body{background:unset} nav{border-bottom:3px solid #89191f} div.svelte-a08hsz div {width:20%; display:inline-flex;} ul.svelte-a08hsz {width:70%; display:inline-flex; float:right; list-style-type:none;} ul.svelte-a08hsz li {padding:0px 15px} a.logo {padding-top:5px;} a.logo div {display:none}"
      
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: bridgewater-state-university.github.io/upptime/
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/Bridgewater-State-University/upptime/master/assets/bsu/images/bsu-red.png
  name: Upptime | Bridgewater State University
  introTitle: "Hello BSU World!!!"
  introMessage: This status page uses **real-time** data from our GitHub repository. No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
